[package]
name = "thermal_rs"
version = "0.1.0"
edition = "2024"
description = "Thermal Conduction Simulation Library"
readme = "README.md"
license = "MIT"

[dependencies]
base64 = "0.22.1"

[features]
cpu_single = []
